version: '3.8'

services:
  gitlab:
    image: 'gitlab/gitlab-ce:16.9.6-ce.0'  # Usando a versão especificada do GitLab CE
    container_name: gitlab
    hostname: 'gitlab.example.com'
    restart: always
    ports:
      - '5050:80'    # Porta HTTP mapeada para 5050 no host
      - '443:443'    # Porta HTTPS
      - '9022:22'    # Porta SSH mapeada para 9022 no host
    volumes:
      - '/srv/gitlab/config:/etc/gitlab'   # Persistência das configurações
      - '/srv/gitlab/logs:/var/log/gitlab' # Persistência dos logs
      - '/srv/gitlab/data:/var/opt/gitlab' # Persistência dos dados
    networks:
      - gitlab

networks:
  gitlab:
    external: true  # Usar a rede externa já existente chamada "gitlab"

